---
site_name: cookiecutter-doge
# site_url: http://www.jieyu.ai
edit_uri: edit/main/docs
repo_url: https://github.com/martibosch/cookiecutter-doge
repo_name: cookiecutter-doge
nav:
    - Home: index.md
theme:
    name: readthedocs
    language: en
plugins:
    - search:
          lang: en
markdown_extensions:
  - mdx_truly_sane_lists
