name: ci

on:
  push:
    paths-ignore: [ "docs/**" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code repository
        uses: actions/checkout@v3

      - name: run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    strategy:
      matrix:
        python-versions: [3.8, 3.9]
        include:
          - miniforge-variant: Mambaforge
            miniforge-version: 4.11.0-4
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: setup conda environment with mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          activate-environment: osmnx-dev
          python-version: ${{ matrix.python-version }}
          condarc-file: ${{ matrix.condarc-file }}
          environment-file: ${{ matrix.environment-file }}
          miniforge-variant: ${{ matrix.miniforge-variant }}
          miniforge-version: ${{ matrix.miniforge-version }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: test with tox
        run:
          tox
        env:
          CONDA_EXE: mamba
